[package]
name = "tomlrex"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "tomlrex"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
toml = "0.5"
rustler = "0.21.0"
lazy_static = "1.0"
